# Whether to enable Nvidia
# Assumes Nvidia drivers are installed
sunshine_nvidia_enable: true

sunshine_server_name: Sunshine

# Directory where Sunshine Docker Compose files and other configuration are copied
sunshine_project_dir: "{{ ansible_user_dir }}/sunshine"

# Directory where Sunshine and other data (eg. Steam game files) are persisted
# Bind mounted in Sunshine container for persistence
# Changing this value will cause to lose track of existing data unless they are moved as well
sunshine_data_dir: "/var/lib/cloudypad/sunshine/data"

# Directory where persistent Sunshine container configuration is stored
# Bind mounted in Sunshine container for persistence
sunshine_persistent_config_dir: "/var/lib/cloudypad/sunshine/conf"

# Directory where user's home directory from container is persisted
sunshine_persistent_home_dir: "/var/lib/cloudypad/sunshine/home"

# Legacy Sunshine data directory
# If data is found in this directory it will be moved to sunshine_data_dir
sunshine_legacy_data_dir: "{{ sunshine_project_dir }}/data"

# Sunshine Web UI username and password (base64 encoded)
# If unset password will have to be set via Sunshine web UI
sunshine_web_username: ""
sunshine_web_password_base64: "" # Password encoded in base64, eg echo -n "<password>" | base64

# Sunshine container image to use 
sunshine_image_tag: "dev"
sunshine_image_repo: "ghcr.io/pierrebeucher/cloudypad/sunshine"

# Whether to force pull images when deploying Docker Compose Sunshine containers
sunshine_compose_pull_images: always

# Keyboard settings
# see docker-compose.yml for more details
sunshine_keyboard_layout: en
sunshine_keyboard_model: ""
sunshine_keyboard_variant: "qwerty"
sunshine_keyboard_options: ""

# Desired locale
sunshine_locale: en_US.UTF-8

# Optional additional Sunshine config
# Use "\n" for multiple lines
# eg. "capture = x11\nfoo = bar"
sunshine_additional_config: ""

# Maximum bitrate in Kbps for Sunshine streaming (max_bitrate config)
sunshine_max_bitrate_kbps: "0"

# Wheher to enable Sunshine container autoheal
# If enabled, Sunshine container will be automatically restarted if it becomes unhealthy
# It may happen the container crashes without exiting (eg. Sunshine server crash), autoheal helps being more resilient
sunshine_autoheal_enable: true
sunshine_autoheal_image: "willfarrell/autoheal:1.2.0@sha256:31f580ef0279eaced5b38d631b08c474d70d8403c1c2fdd6ddcf2e879d5f3f7c"