# Whether to enable Nvidia
# Assumes Nvidia drivers are installed
sunshine_nvidia_enable: true

sunshine_server_name: Sunshine

# Directory where Sunshine Docker Compose files and other configuration are copied
sunshine_project_dir: "{{ ansible_user_dir }}/sunshine"

# Directory where Sunshine and other data (eg. Steam game files) are persisted
# Bind mounted in Sunshine container for persistence
# Changing this value will cause to lose track of existing data unless they are moved as well
sunshine_data_dir: "{{ sunshine_project_dir }}/data"

# Sunshine Web UI username and password (base64 encoded)
# If unset password will have to be set via Sunshine web UI
sunshine_web_username: ""
sunshine_web_password_base64: "" # Password encoded in base64, eg echo -n "<password>" | base64

# Sunshine container image to use 
sunshine_image_tag: "dev"
sunshine_image_repo: "ghcr.io/pierrebeucher/cloudypad/sunshine"

# Whether to force pull images when deploying Docker Compose Sunshine containers
sunshine_compose_pull_images: true