# Wolf for Nvidia
services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:stable@sha256:f33baf84771970653f730661a4ccef997bbfb2021b70588719936cefdaedba04
    environment:
      XDG_RUNTIME_DIR: /tmp/sockets
      NVIDIA_DRIVER_VOLUME_NAME: ${NVIDIA_VOLUME_NAME}
      HOST_APPS_STATE_FOLDER: /etc/wolf
      WOLF_LOG_LEVEL: DEBUG
    volumes:
      # Used by other containers created by wolf. Do not change
      - /etc/wolf/:/etc/wolf:rw
      - /etc/wolf/cfg:/etc/wolf/cfg:rw
      - /tmp/sockets:/tmp/sockets:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/shm:/dev/shm:rw
      - /dev/input:/dev/input:rw
      - /run/udev:/run/udev:rw
      - nvidia-driver-vol:/usr/nvidia:rw
    devices:
      - /dev/dri
      - /dev/uinput
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
      - /dev/nvidia-caps/nvidia-cap1
      - /dev/nvidia-caps/nvidia-cap2
      - /dev/nvidiactl
      - /dev/nvidia0
      - /dev/nvidia-modeset
    device_cgroup_rules:
      - 'c 13:* rmw'
    network_mode: host
    restart: unless-stopped

volumes:
  # Volume populated with nvidia drivers 
  nvidia-driver-vol:
    external: true
    name: ${NVIDIA_VOLUME_NAME}