- name: import Paperspace tasks
  import_tasks: paperspace.yml
  when: cloudypad_provider is defined and cloudypad_provider == "paperspace"

- name: import Scaleway tasks
  import_tasks: scaleway.yml
  when: cloudypad_provider is defined and cloudypad_provider == "scaleway"


