- name: import Paperspace tasks
  import_tasks: paperspace.yml
  when: cloudypad_provider is defined and cloudypad_provider == "paperspace"

- name: import Scaleway tasks
  import_tasks: scaleway.yml
  when: cloudypad_provider is defined and cloudypad_provider == "scaleway"

- name: Create Docker service directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'

- name: Configure Docker service limits
  copy:
    dest: /etc/systemd/system/docker.service.d/limits.conf
    content: |
      [Service]
      LimitNOFILE=65536
      LimitNPROC=65536
    mode: '0644'

- name: Reload systemd configuration
  command: systemctl daemon-reload

- name: Restart Docker service
  command: systemctl restart docker