- name: import Paperspace tasks
  import_tasks: paperspace.yml
  when: cloudypad_provider is defined and cloudypad_provider == "paperspace"

- name: import Scaleway tasks
  import_tasks: scaleway.yml
  when: cloudypad_provider is defined and cloudypad_provider == "scaleway"

- name: Disable ulimit commands in Docker init script
  replace:
    path: /etc/init.d/docker
    regexp: '(\s*)ulimit (.*)$'
    replace: '\1# ulimit \2  # Disabled for container compatibility'
    backrefs: yes
  when: cloudypad_provider is defined and cloudypad_provider == "dummy"


