---
# On Paperspace with Ubuntu 22.04, the apt source for Paperspace is buggy (invalid GPG key)
# causing subsequent failure on apt cache update
# removing it here to avoid issues
- name: Remove paperspace apt source (if any)
  become: true
  file:
    state: absent
    path: /etc/apt/sources.list.d/paperspace.list