- name: SSH Provider - Check Ubuntu version
  ansible.builtin.pause:
    prompt: >-
      WARNING: Cloudy Pad is designed to run on Ubuntu 22.04 or 24.04.
      Detected version: {{ ansible_distribution }} {{ ansible_distribution_version }}.
      Some features may not work correctly. Do you want to continue?
  when: ansible_distribution != "Ubuntu" or ansible_distribution_major_version not in ["22", "24"]

- name: SSH Provider - remove unwanted apt sources (if any)
  become: true
  file:
    state: absent
    path: "{{ item }}"
  loop:
    # out of date, cause apt update failure
    - /etc/apt/sources.list.d/nvidia-docker.list
    - /etc/apt/sources.list.d/cuda.list

# Scaleway comes with pre-installed NVIDIA packages
# But we want to use our fixed, reproducible package install method with nvidia role
- name: SSH Provider - remove unwanted apt NVIDIA packages
  become: true
  register: ssh_apt_remove_nvidia_packages
  ansible.builtin.apt:
    name:
      - libnvidia-cfg1-*
      - libnvidia-compute-*
      - nvidia-compute-utils-*
      - nvidia-firmware-*
      - nvidia-headless-no-dkms-*
      - nvidia-kernel-common-*
      - nvidia-kernel-source-*
      - nvidia-utils-*
    state: absent
    purge: yes

- name: SSH Provider - apt autoremove 
  become: true
  when: ssh_apt_remove_nvidia_packages.changed
  ansible.builtin.apt:
    autoremove: yes

- name: SSH Provider - clean apt cache
  become: true
  when: ssh_apt_remove_nvidia_packages.changed
  ansible.builtin.apt:
    clean: yes
