
- name: Install Xorg and related packages
  apt:
    name:
      - xorg
      - openbox
      - x11-xserver-utils
      - xinit
    state: present
    update_cache: yes

- name: Remove xserver-xorg-video-nouveau
  apt:
    name: xserver-xorg-video-nouveau
    state: absent