services:
  cloudy:
    image: {{ sunshine_image_repo }}:{{ sunshine_image_tag }}
    # This container name is used by various scripts and functions to identify the container
    # Don't change it
    container_name: cloudy
    # Need generous shared memory size as some services (eg. Steam) require a lot
    # Half available memory (as is the case for most Linux distros)
    shm_size: "{{ (ansible_memtotal_mb / 2) | int }}M"
    # Privileged required to run Steam with bwrap (sandboxing)
    privileged: true
    # Always start container on machine startup unless specifically stopped
    restart: unless-stopped
    # uinput is used by Susnhine to emulate input devices (keyboard, mouse, etc.)
    devices:
    - /dev/uinput
    
    volumes:
    # Allow input access from container (keyboard, mouse, etc
    # TODO maybe not required from fully headless setup
    - /dev/input:/dev/input
    
    # Cloudy Pad data and XDG_DATA_HOME where data should be persisted (game files, Sunshine state, etc.)
    - "{{ sunshine_data_dir }}:/cloudy/data"

    # Keep xfce4 config on host as user may customize it (eg. keyboard layout)
    - "{{ sunshine_persistent_config_dir }}/xfce4:/cloudy/conf/xfce4"

    # Keep Heroic config and data
    - "{{ sunshine_persistent_config_dir }}/heroic:/cloudy/conf/heroic"

    # Keep user's home directory
    # Some important data are stored in $HOME by numerous apps (like Heroic or Lutris)
    # persisting this folder makes sense to keep user's data across container recreation
    - "{{ sunshine_persistent_home_dir }}:/home/cloudy"

    # Allow container to read/write/manage attributes on character device 13
    # 13 matches /dev/input mouse, keyboard, etc. devices
    # thus allowing process in container to manage input which we need for Sunshine
    device_cgroup_rules:
      - 'c 13:* rmw'
    ports:
      - "47984:47984/tcp" # HTTPS
      - "47989:47989/tcp" # HTTP
      - "47990:47990/tcp" # Web
      - "48010:48010/tcp" # RTSP

      - "47998:47998/udp" # Video
      - "47999:47999/udp" # Control
      - "48000:48000/udp" # Audio
      - "48002:48002/udp" # Mic (unused)
    environment:
      # Desired keyboard layout
      # See available layouts: https://man.archlinux.org/man/xkeyboard-config.7#LAYOUTS
      # Passed to Xorg config as per https://wiki.archlinux.org/title/Xorg/Keyboard_configuration#Using_X_configuration_files
      #
      # Variables are passed to template overlay/cloudy/conf/x11/templates/00-keyboard.conf
      CLOUDYPAD_KEYBOARD_LAYOUT: {{ sunshine_keyboard_layout }}
      CLOUDYPAD_KEYBOARD_MODEL: {{ sunshine_keyboard_model }}
      CLOUDYPAD_KEYBOARD_VARIANT: {{ sunshine_keyboard_variant }}
      CLOUDYPAD_KEYBOARD_OPTIONS: {{ sunshine_keyboard_options }}

      # Desired locale
      CLOUDYPAD_LOCALE: {{ sunshine_locale }}

      # Sunshine Web UI password
      # If unset or empty, can be set via Web UI directly
      SUNSHINE_WEB_PASSWORD_BASE64: "{{ sunshine_web_password_base64 }}"
      SUNSHINE_WEB_USERNAME: "{{ sunshine_web_username }}"
      SUNSHINE_SERVER_NAME: >-
        {{ sunshine_server_name | to_yaml | indent(8) }}

      # Optional additional Sunshine config
      # Use "\n" for multiple lines
      # eg. "capture = x11\nfoo = bar"
      CLOUDYPAD_SUNSHINE_ADDITIONAL_CONFIG: "{{ sunshine_additional_config }}"

      # Sunshine maximum bitrate in Kbps
      # If unset, Sunshine will use its default bitrate settings
      CLOUDYPAD_SUNSHINE_MAX_BITRATE: "{{ sunshine_max_bitrate_kbps }}"
