# Docker Compose override to enable Nvidia GPU in container
services:
  cloudy:
    runtime: nvidia
    environment:
      # Enable Nvidia to trigger specific behaviors in container
      NVIDIA_ENABLE: true
      # Nvidia driver version matching host driver
      NVIDIA_DRIVER_VERSION: "{{ sunshine_nvidia_driver_version }}"

      # Nvidia PCI bus ID suitable for X server config
      # Must be in format "bus@domain:device.function"
      # Use lspci to show available GPUs
      # We need to enforce it here as X may fail to auto-detect proper PCI in some environments (eg. Azure)
      NVIDIA_PCI_BUS_ID: "{{ nvidia_pci_bus_id }}"

      # Nvidia driver capabilities required to run games
      # Set all capabilities to enable all features, including graphics, video and display
      # See https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/docker-specialized.html
      NVIDIA_DRIVER_CAPABILITIES: all

{% if nvidia_gpu_model in nvidia_datacenter_gpu_models %}
      # Datacenter (Tesla) GPUs have a maximum resolution of 2560x1600
      # See https://github.com/PierreBeucher/cloudypad/issues/144
      # and https://forums.developer.nvidia.com/t/datacenter-gpus-are-capped-to-2560x1600-resolution-for-headless-output-unlike-consumer-gpus/309845
      CLOUDYPAD_SCREEN_MAX_WIDTH: "2560"
      CLOUDYPAD_SCREEN_MAX_HEIGHT: "1600"
{% endif %}
    deploy:
      resources:
        reservations:
          # Enable GPU in container
          # See https://docs.docker.com/compose/how-tos/gpu-support/#enabling-gpu-access-to-service-containers
          devices:
            - capabilities: [gpu]