all:
  hosts:
    # Vagrant VM
    "192.168.56.43":
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/default/virtualbox/private_key
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      cloudypad_web_fqdn: "192.168.56.42"
      sunshine_nvidia_enable: false
      sunshine_compose_pull_images: never
      sunshine_image_tag: local