all:
  hosts:
    # Vagrant VM
    "192.168.56.43":
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/default/virtualbox/private_key
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      
      sunshine_server_name: dev-vagrant
      sunshine_nvidia_enable: false
      sunshine_compose_pull_images: never
      sunshine_image_tag: local

      autostop_timeout_seconds: 3600 # 1h

      sunshine_keyboard_layout: fr
      sunshine_keyboard_variant: azerty
      sunshine_keyboard_model: pc104
      sunshine_keyboard_options: terminate:ctrl_alt_bksp

      sunshine_web_username: sunshine
      
      # Password with special characters
      # echo -n '@!/:,?!*#'"'"'€`_\µ$="foo' | base64 | base64 -d
      # => @!/:,?!*#'€`_\µ$="foo
      sunshine_web_password_base64: QCEvOiw/ISojJ+KCrGBfXMK1JD0iZm9v
    
      # sunshine_keyboard_layout: fr
      # sunshine_keyboard_variant: mac,azerty
      # sunshine_keyboard_model: macbook78
      # sunshine_keyboard_options: ""

      sunshine_locale: fr_FR.UTF-8

      # Dev environment specifics
      # Vagrant doesn't have a GPU access and Sunshine default to KMS capture
      # which somehow fails in Vagrant VM + container and make X11 and desktop crash
      # for unknown reason.
      #
      # This is related to /dev/dri* access: when Sunshine doesn't have access to
      # /dev/dri* it will fallback to X11 capture as it can't read it, but since
      # Sunshine user has access to /dev/* it will try to use KMS capture which make
      # use of DRI. This somehow crash the X11 and desktop process for unknown reason.
      # Forcing to use X11 capture workaround the issue.
      sunshine_additional_config: "capture = x11"
      
      cloudypad_provider: "vagrant"
      