all:
  hosts:
    # Vagrant VM
    "192.168.56.43":
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/default/virtualbox/private_key
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      
      sunshine_server_name: dev-vagrant
      sunshine_nvidia_enable: false
      sunshine_compose_pull_images: never
      sunshine_image_tag: local

      autostop_timeout_seconds: 3600 # 1h

      sunshine_keyboard_layout: fr
      sunshine_keyboard_variant: azerty
      sunshine_keyboard_model: pc104
      sunshine_keyboard_options: terminate:ctrl_alt_bksp
      
      sunshine_locale: en_US.utf8

      cloudypad_provider: "vagrant"
      