# ---
- name: Install dependencies for Sunshine
  apt:
    name:
      - libevdev2
      - libopus0
      - libpulse0
      - libva2
      - libva-drm2
      - libwayland-client0
      - miniupnpc
      - libayatana-appindicator3-1
      - libnotify4
    state: present
    update_cache: yes


- name: Download Sunshine deb package
  get_url:
    url: https://github.com/LizardByte/Sunshine/releases/download/v2025.118.151840/sunshine-ubuntu-24.04-amd64.deb
    dest: /tmp/sunshine.deb

# Deb installer also:
# - set cap_sys_admin+p
# - set udev rules in /lib/udev/rules.d/60-sunshine.rules
- name: Install Sunshine deb package
  apt:
    deb: /tmp/sunshine.deb

- name: Load uinput module
  modprobe:
    name: uinput
    state: present

- name: Install nvidia virtual display required packages
  apt:
    name:
      # Required for Nvidia virtual display
      - mesa-utils
      - mesa-vulkan-drivers
      - libgl1-mesa-dri
    state: present

- name: setup X config with dummy display
  copy:
    src: x11-virtscreen.conf
    dest: /etc/X11/xorg.conf.d/30-virtscreen.conf

# - name: Create systemd user service for Sunshine
#   copy:
#     dest: ~/.config/systemd/user/sunshine.service
#     content: |
#       [Unit]
#       Description=Sunshine self-hosted game stream host for Moonlight.
#       StartLimitIntervalSec=500
#       StartLimitBurst=5

#       [Service]
#       ExecStart=/usr/local/bin/sunshine
#       Restart=on-failure
#       RestartSec=5s

#       [Install]
#       WantedBy=default.target

# - name: Start Sunshine service
#   systemd:
#     scope: user
#     daemon_reload: yes
#     name: sunshine
#     state: started
#     enabled: yes