# ---
- name: Install dependencies for Sunshine
  apt:
    name:
      - libevdev2
      - libopus0
      - libpulse0
      - libva2
      - libva-drm2
      - libwayland-client0
      - miniupnpc
      - libayatana-appindicator3-1
      - libnotify4
    state: present
    update_cache: yes

- name: Download Sunshine deb package
  get_url:
    url: https://github.com/LizardByte/Sunshine/releases/download/v2025.118.151840/sunshine-ubuntu-24.04-amd64.deb
    dest: /tmp/sunshine.deb

# Deb installer also:
# - set cap_sys_admin+p
# - set udev rules in /lib/udev/rules.d/60-sunshine.rules
- name: Install Sunshine deb package
  apt:
    deb: /tmp/sunshine.deb

- name: Load uinput module
  modprobe:
    name: uinput
    state: present

- name: Install nvidia virtual display required packages
  apt:
    name:
      # Required for Nvidia virtual display
      - mesa-utils
      - mesa-vulkan-drivers
      - libgl1-mesa-dri
    state: present

- name: Install GDM display manager
  apt:
    name:
    - gdm3
    - ubuntu-desktop-minimal
    state: present
    update_cache: yes

- name: Configure GDM for autologin
  copy:
    src: gdm.conf
    dest: /etc/gdm3/custom.conf
    owner: root
    group: root
    mode: '0644'
  register: gdm_config

- name: Restart display-manager
  systemd:
    name: display-manager
    state: restarted
  when: gdm_config is changed

- name: Ensure home .config directory exists
  file:
    path: /home/sunshine/.config
    state: directory
    owner: sunshine
    group: sunshine
    mode: '0755'

- name: Ensure home sunshine config directory exists
  file:
    path: /home/sunshine/.config/sunshine
    state: directory
    owner: sunshine
    group: sunshine
    mode: '0755'

- name: copy Sunshine config file
  ansible.builtin.copy:
    src: sunshine.conf
    dest: /home/sunshine/.config/sunshine/sunshine.conf
    owner: sunshine
    group: sunshine
    mode: '0660'

- name: Ensure sunshine user exists
  ansible.builtin.user:
    name: sunshine
    home: /home/sunshine
    shell: /bin/bash
    groups: input,video,render # ,sound
    password: $6$Aib4IX3lIJAcbpis$yMc2n5Ii.Xwzh74dV8w.MqP/gn8Xm8R0MUE4JYYUJoP2yxJmZL3dwV07DAYhDPbe151ZhuTIXYYQZFFpAAB.p/
    state: present
    createhome: yes

- name: Setup sunshine systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/sunshine.service
    content: |
      [Unit]
      Description=Sunshine server
      WantedBy=graphical-session.target
      PartOf=graphical-session.target
      Wants=graphical-session.target
      After=graphical-session.target
      StartLimitIntervalSec=500
      StartLimitBurst=5

      [Service]
      ExecStart=/usr/bin/sunshine
      Restart=on-failure
      RestartSec=5s
      User=sunshine
      Group=sunshine

      [Install]
      WantedBy=graphical-session.target

- name: Reload systemd to apply sunshine service
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start sunshine service
  # become: true
  # become_user: sunshine
  ansible.builtin.systemd:
    name: sunshine.service
    enabled: true
    state: started
    # scope: user

- name: setup X config with dummy display
  copy:
    src: x11-virtscreen.conf
    dest: /etc/X11/xorg.conf.d/30-virtscreen.conf

# - name: Create systemd user service for Sunshine
#   copy:
#     dest: ~/.config/systemd/user/sunshine.service
#     content: |
#       [Unit]
#       Description=Sunshine self-hosted game stream host for Moonlight.
#       StartLimitIntervalSec=500
#       StartLimitBurst=5

#       [Service]
#       ExecStart=/usr/local/bin/sunshine
#       Restart=on-failure
#       RestartSec=5s

#       [Install]
#       WantedBy=default.target

# - name: Start Sunshine service
#   systemd:
#     scope: user
#     daemon_reload: yes
#     name: sunshine
#     state: started
#     enabled: yes