---
- name: Test NVIDIA PCI Bus ID transformation
  hosts: localhost
  gather_facts: false

  tasks:
    - set_fact:
        nvidia_pci_bus_id_raw: "00000000:81:00.0"

    - debug:
        msg: "Raw NVIDIA PCI BUS ID: {{ nvidia_pci_bus_id_raw }}"

    # nvidia_pci_bus_id_raw looks like "0001:00:00.0" in format "domain:bus:device.function" with base 16 (hexadecimal) numbers
    # nvidia_pci_bus_id is suitable X Server config which needs format "PCI:bus@domain:device:function" with base 10 (decimal) numbers
    # See https://www.x.org/releases/X11R7.7/doc/man/man5/xorg.conf.5.xhtml and https://unix.stackexchange.com/a/633709
    - name: Extract and transform PCI details
      set_fact:
        nvidia_pci_domain: "{{ nvidia_pci_bus_id_raw.split(':')[0] | int(base=16) | string }}"
        nvidia_pci_bus: "{{ nvidia_pci_bus_id_raw.split(':')[1] | int(base=16) | string }}"
        nvidia_pci_device: "{{ nvidia_pci_bus_id_raw.split(':')[2].split('.')[0] | int(base=16) | string }}"
        nvidia_pci_function: "{{ nvidia_pci_bus_id_raw.split(':')[2].split('.')[1] | int(base=16) | string }}"

    - set_fact:
        nvidia_pci_bus_id: "PCI:{{ nvidia_pci_bus }}@{{ nvidia_pci_domain }}:{{ nvidia_pci_device }}:{{ nvidia_pci_function }}"

    - debug:
        msg: "Found NVIDIA PCI BUS ID: {{ nvidia_pci_bus_id }}"

    - name: Show all extracted values
      debug:
        msg: |
          Raw input: {{ nvidia_pci_bus_id_raw }}
          Domain: {{ nvidia_pci_domain }} (hex: {{ nvidia_pci_bus_id_raw.split(':')[0] }})
          Bus: {{ nvidia_pci_bus }} (hex: {{ nvidia_pci_bus_id_raw.split(':')[1] }})
          Device: {{ nvidia_pci_device }} (hex: {{ nvidia_pci_bus_id_raw.split(':')[2].split('.')[0] }})
          Function: {{ nvidia_pci_function }} (hex: {{ nvidia_pci_bus_id_raw.split(':')[2].split('.')[1] }})
          Final PCI Bus ID: {{ nvidia_pci_bus_id }}
