name: Release

on:
  push:
    tags:
      - '*'

jobs:
  docker-build-core:
    name: Docker Build Core
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Core container image
        run: CLOUDYPAD_BUILD_CORE_IMAGE_TAG=${GITHUB_REF_NAME#v} nix develop -c task build-core-container-release

  docker-build-sunshine:
    name: Docker Build Sunshine
    runs-on: self-hosted
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Sunshine container image
        run: CLOUDYPAD_BUILD_SUNSHINE_IMAGE_TAG=${GITHUB_REF_NAME#v} nix develop -c task build-sunshine-container-release
