name: Integration Tests

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - master

env:
  CLOUDYPAD_LOG_LEVEL: "3"

jobs:
  integ-test:
    name: Integration tests
    runs-on: self-hosted
    
    steps:          
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - run: nix develop -c pnpm i

      # Only S3 integ test on CI for now as it only depends on container not external accounts and runs quickly
      - name: Run integration tests
        run: nix develop -c task test-integ-s3-side-effects
